In [1]:
import torch
import torchvision
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms

C:\Users\vivek\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.7.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\vivek\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.2' currently installed).
  from pandas.core import (


In [55]:
torch.manual_seed(1)
print(torch.__version__)


2.1.1+cpu


## Important Tensor Functions

In [58]:
torch.zeros(4,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [59]:
torch.ones(4,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [60]:
torch.eye(4,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [61]:
torch.rand(4,4)

tensor([[0.7576, 0.2793, 0.4031, 0.7347],
        [0.0293, 0.7999, 0.3971, 0.7544],
        [0.5695, 0.4388, 0.6387, 0.5247],
        [0.6826, 0.3051, 0.4635, 0.4550]])

In [62]:
torch.randn(4,4)


tensor([[-0.6970, -1.1608,  0.6995,  0.1991],
        [ 0.8657,  0.2444, -0.6629,  0.8073],
        [ 1.1017, -0.1759, -2.2456, -1.4465],
        [ 0.0612, -0.6177, -0.7981, -0.1316]])

In [63]:
torch.arange(0, 3, step=0.3)


tensor([0.0000, 0.3000, 0.6000, 0.9000, 1.2000, 1.5000, 1.8000, 2.1000, 2.4000,
        2.7000])

## Matrix Operations

In [64]:
x11 = torch.randn(3,5)
x12 = torch.randn(5,5)
x13 = torch.randn(5,3)
x11, x12, x13


(tensor([[-0.4212, -0.5107, -1.5727, -0.1232,  3.5870],
         [-1.8313,  1.5987, -1.2770,  0.3255, -0.4791],
         [ 1.3790,  2.5286,  0.4107, -0.9880, -0.9081]]),
 tensor([[-0.0255, -1.0233, -0.5962, -1.0055, -0.2106],
         [-0.0075,  1.6734,  0.0103, -0.7040, -1.4746],
         [-0.3416, -0.3003,  1.3075, -1.1628,  0.1196],
         [-0.1631,  0.6614, -0.9301,  1.4301,  0.4208],
         [-0.3538,  0.7639, -0.5890, -0.7636,  1.3352]]),
 tensor([[ 0.5423, -0.5581, -0.3964],
         [ 1.4130, -2.6119, -1.6396],
         [ 2.3906, -0.5024,  0.0476],
         [-1.1322, -0.0179,  0.1280],
         [-0.5552, -0.4575, -1.9599]]))

In [67]:
torch.mm(x11,x12)

tensor([[-0.6972,  2.7073, -3.8084, -0.3035,  5.3911],
        [ 0.5873,  4.7820, -0.5820,  3.0323, -2.6273],
        [ 0.2879,  1.3496,  1.1948, -4.3638, -5.5980]])

In [68]:
x11.mm(x12)


tensor([[-0.6972,  2.7073, -3.8084, -0.3035,  5.3911],
        [ 0.5873,  4.7820, -0.5820,  3.0323, -2.6273],
        [ 0.2879,  1.3496,  1.1948, -4.3638, -5.5980]])

In [69]:
torch.matmul(x11,x12)

tensor([[-0.6972,  2.7073, -3.8084, -0.3035,  5.3911],
        [ 0.5873,  4.7820, -0.5820,  3.0323, -2.6273],
        [ 0.2879,  1.3496,  1.1948, -4.3638, -5.5980]])

In [70]:
torch.mul(x11,x12)

RuntimeError: The size of tensor a (3) must match the size of tensor b (5) at non-singleton dimension 0

In [71]:
x14 = torch.randn(3, 4)
v = torch.randn(4)


In [74]:
torch.mv(x14,v) ## matrix vector product

tensor([-3.8167, -0.9935, -3.4006])

In [75]:
x15 = torch.randn(10,3,4)
x16 = torch.randn(10,4,5)

torch.bmm(x15, x16).size()
# Performs a batch matrix-matrix product of matrices

torch.Size([10, 3, 5])

## Tensor vs Variable

In [78]:
import torch
from torch.autograd import Variable

In [79]:
tensor=torch.randn(2,2)
x=Variable(tensor,requires_grad=True)

tensor, x

(tensor([[-1.0361,  0.0602],
         [-1.6259,  0.4273]]),
 tensor([[-1.0361,  0.0602],
         [-1.6259,  0.4273]], requires_grad=True))

In [80]:
x.sum(),x.sqrt(), x**2, x

(tensor(-2.1745, grad_fn=<SumBackward0>),
 tensor([[   nan, 0.2453],
         [   nan, 0.6537]], grad_fn=<SqrtBackward0>),
 tensor([[1.0734, 0.0036],
         [2.6437, 0.1826]], grad_fn=<PowBackward0>),
 tensor([[-1.0361,  0.0602],
         [-1.6259,  0.4273]], requires_grad=True))

In [81]:
x.data

tensor([[-1.0361,  0.0602],
        [-1.6259,  0.4273]])

In [82]:
x.requires_grad

True

In [83]:
x.grad

In [84]:
x.grad_fn

In [85]:
x.volatile

C:\Users\vivek\AppData\Local\Temp/ipykernel_11652/2818851177.py:1: UserWarning: volatile was removed (Variable.volatile is always False)
  x.volatile


False

In [87]:
x = Variable(torch.FloatTensor([13.]),requires_grad=True)

y = x**3 + 3

z = Variable(torch.FloatTensor([5.]))

print(x.requires_grad,z.requires_grad)

True False


In [89]:
y.grad_fn.next_functions[0][0]
y.backward()

In [90]:
x,x.grad

(tensor([13.], requires_grad=True), tensor([507.]))

In [91]:
x.grad,x.grad.data.zero_(), x.grad

(tensor([0.]), tensor([0.]), tensor([0.]))

In [92]:
x1 = Variable(torch.ones(2), requires_grad = True)
x2 = Variable(torch.ones(2))


In [93]:
y = x1 * 2 + x2
print(y)
print(y.requires_grad)

tensor([3., 3.], grad_fn=<AddBackward0>)
True


In [94]:
y.backward(torch.Tensor([1,1]))

x1.grad

tensor([2., 2.])

In [95]:
x2.grad

In [96]:
x1.grad.data.zero_() ## sets gradients to zero

tensor([0., 0.])

## Simple 1D example

In [56]:
x=torch.tensor(1.,requires_grad=True)
w=torch.tensor(2.,requires_grad=True)
b=torch.tensor(2.,requires_grad=True)

In [57]:
x.type(),x.size(),x.numel()

('torch.FloatTensor', torch.Size([]), 1)

In [38]:
print(x)
print(w)
print(b)

tensor(1., requires_grad=True)
tensor(2., requires_grad=True)
tensor(2., requires_grad=True)


In [39]:
y=w*x+b
print(y)

tensor(4., grad_fn=<AddBackward0>)


In [40]:
y.backward(retain_graph=True)


In [41]:
print(x)
print(w)
print(b)

tensor(1., requires_grad=True)
tensor(2., requires_grad=True)
tensor(2., requires_grad=True)


## Simple 2 D example with a Linear layer

In [42]:
x=torch.randn(10,3)
y=torch.rand(10,2)

linear=nn.Linear(3,2)

print('w',linear.weight)
print('b',linear.bias)

w Parameter containing:
tensor([[-0.2229, -0.4551, -0.4546],
        [ 0.3503,  0.5745,  0.2357]], requires_grad=True)
b Parameter containing:
tensor([0.2774, 0.4527], requires_grad=True)


In [43]:
criterion=nn.MSELoss()
optimizer=torch.optim.SGD(linear.parameters(),lr=0.01)


In [44]:
pred=linear(x)
loss=criterion(pred,y)

print('loss initially',loss.item()) ## get value

loss initially 0.5654733777046204


In [45]:
loss.backward()

In [46]:
print(linear.weight.grad)
print(linear.bias.grad)

tensor([[-0.0537, -0.4483, -0.8926],
        [ 0.0576,  0.4482,  0.3318]])
tensor([-0.2893, -0.0351])


In [47]:
optimizer.step() ## 1-step gradient descent

In [48]:
pred=linear(x)
loss=criterion(pred,y)

print('loss after 1 epoch',loss.item())

loss after 1 epoch 0.5515884160995483


In [50]:
optimizer.step()

pred=linear(x)
loss=criterion(pred,y)

print('loss after 2 epoch',loss.item())

loss after 2 epoch 0.537927508354187


## From Numpy to Tensor

In [53]:
x=np.array([[1,2],[3,4]])

y=torch.from_numpy(x)

print(y)

z=y.numpy()

print(z)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
[[1 2]
 [3 4]]


## Input Pipeline

In [54]:
train_dataset = torchvision.datasets.CIFAR10(root='../../data/',
                                             train=True, 
                                             transform=transforms.ToTensor(),
                                             download=True)

# Fetch one data pair (read data from disk).
image, label = train_dataset[0]
print (image.size())
print (label)

100%|███████████████████████████████████████████████████████████████| 170498071/170498071 [01:42<00:00, 1670685.90it/s]


Extracting ../../data/cifar-10-python.tar.gz to ../../data/
torch.Size([3, 32, 32])
6


## Finetuning a pre-trained model

In [97]:
resnet = torchvision.models.resnet18(pretrained=True)

# If you want to finetune only the top layer of the model, set as below.
for param in resnet.parameters():
    param.requires_grad = False

# Replace the top layer for finetuning.
resnet.fc = nn.Linear(resnet.fc.in_features, 100)  # 100 is an example.

# Forward pass.
images = torch.randn(64, 3, 224, 224)
outputs = resnet(images)
print (outputs.size())     # (64, 100)

C:\Users\vivek\anaconda3\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\vivek\anaconda3\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to C:\Users\vivek/.cache\torch\hub\checkpoints\resnet18-f37072fd.pth
100%|█████████████████████████████████████████████████████████████████████████████| 44.7M/44.7M [00:11<00:00, 4.11MB/s]


torch.Size([64, 100])
